// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: core/command.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from core/command.proto</summary>
public static partial class CommandReflection {

  #region Descriptor
  /// <summary>File descriptor for core/command.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static CommandReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJjb3JlL2NvbW1hbmQucHJvdG8aIGdvb2dsZS9wcm90b2J1Zi9kZXNjcmlw",
          "dG9yLnByb3RvGhpnb29nbGUvcHJvdG9idWYvdHlwZS5wcm90bzoyCgdkYXRh",
          "X2lkEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25zGNCGAyABKAVQ",
          "AFABYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TypeReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { CommandExtensions.DataId }, null));
  }
  #endregion

}
/// <summary>Holder for extension identifiers generated from the top level of core/command.proto</summary>
public static partial class CommandExtensions {
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, int> DataId =
    new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, int>(50000, pb::FieldCodec.ForInt32(400000, 0));
}


#endregion Designer generated code
